# Site settings
title: JEFworks Lab
email: jeanfan@jhu.edu
description: "Lab website of Prof. Jean Fan and team work at Johns Hopkins University"

baseurl: "" # the subpath of your site, e.g. /blog/
url: 'http://jefworks-lab.github.io/'
google_analytics: 'UA-35232680-3'

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: custom

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: _papers
    type: papers
  values:
    layout: paper
    sectionid: publications
- scope:
    path: _news
    type: news
  values:
    layout: pages
    sectionid: announcements
- scope:
    path: _team
    type: team
  values:
    layout: pages
    sectionid: team

collections:
  papers:
    permalink: /papers/:year/:month/:day/:title/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  news:
    permalink: /announcements/:year/:month/:day/:title/
    output: true
  team:
    permalink: /team/:title/
    output: true
