# Site settings
title: Jean Fan
description: "Bioinformatics and Integrative Genomics PhD Student at Harvard University"
url: 'http://jefworks.github.io/'
baseurl: ''
google_analytics: 'UA-35232680-3'
disqus_shortname: 'jefworks'
simple_search: https://www.google.com/search
subscribe_rss: /atom.xml
excerpt_link: "Continue reading &#8230;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"
#titlecase: true       # Converts page and post titles to titlecase

author:
  name: 'Jean Fan'
  email: jeanfan@fas.harvard.edu
  github_username: jefworks
  linkedin_username: jeanfan
  twitter_username: jefworks
  ig_username: jefworks

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-compose', 'jemoji']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
